version: '3.8'

services:
  app:
    image: ghcr.io/smirnoffmg/partner:main
    container_name: assistant-container
    env_file:
      - .env
    restart: always
    depends_on:
      - db

  db:
    image: postgres:13
    container_name: assistant-db
    env_file:
      - .env
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

volumes:
  pgdata:
